#!/Users/Anthony/code/scopely/quarantine/env/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'amsin==0.1.4','console_scripts','amsin'
__requires__ = 'amsin==0.1.4'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('amsin==0.1.4', 'console_scripts', 'amsin')()
    )
